name: ratkai
version: 0.1.0
category: game
license: GPL-3

extra-source-files:
  - README.md
  - import/ZX0/src/*.h
  - import/ZX0/src/*.c
  
dependencies:
  - base
  - bytestring
  - filepath
  - directory
  - binary
  - optparse-applicative
  - split
  - containers
  - prettyprinter
  - array
  - mtl
  - fgl
  - graphviz
  - rev-state
  - exceptions
  - pqueue
  - extra

library:
  source-dirs: src
  
executables:
  ratkai-homelab2:
    main: homelab2.hs
    source-dirs: z80
    dependencies:
      - z80
      - ratkai

  ratkai-tvc:
    main: tvc.hs
    source-dirs: z80
    dependencies:
      - z80
      - ratkai
    c-sources:
      - import/ZX0/src/compress.c
      - import/ZX0/src/optimize.c
      - import/ZX0/src/memory.c

  ratbc-disasm:
    main: src/ratbc-disasm.hs
    dependencies:
      - ratkai
    
  ratbc-asm:
    main: src/ratbc-asm.hs
    dependencies:
      - ratkai

  ratbc-hl2-asm:
    main: src/ratbc-hl2-asm.hs
    dependencies:
      - ratkai

  ratbc-hl2-play:
    main: src/ratbc-hl2-play.hs
    dependencies:
      - ratkai
      - haskeline

  ratbc-tvc-play:
    main: src/ratbc-tvc-play.hs
    dependencies:
      - ratkai
      - haskeline

  ratbc-tvc-asm:
    main: src/ratbc-tvc-asm.hs
    dependencies:
      - ratkai

  ratbc-tvc-colors:
    main: src/ratbc-tvc-colors.hs
    dependencies:
      - monomer
      - lens
      - optparse-applicative
      - ratkai
      - text-show
